Develop
hm-choi/uni-henn pull request #10
Opened 2023-11-16 04:27 UTC by JihunSKKU

2023-11-16 04:29 UTC, JihunSKKU commented
Code refactoring & Change training code & Add ecg dataset

2023-11-16 06:55 UTC, bindon requested changes
service쪽을 좀 고치면 중복된 코드들도 줄이고 재사용이 가능할 것으로 보이네요
일단 이부분을 해보고 다시 해볼까요?
현재 develop -> main PR인데, feat -> develop에서 할만한 내용이네요 😭

2023-11-16 06:55 UTC, bindon commented on M1_test.py
> +import torch.nn.functional as F
import alias를 할당할 때 공식 약어가 있는 경우에만 사용하라고 하네요
https://google.github.io/styleguide/pyguide.html#224-decision
근데 F를 쓰는데가 있나요 😁

2023-11-16 06:55 UTC, bindon commented on M1_test.py
> +        self.FC2 = torch.nn.Linear(64, 10)
기본값으로 할당해놓은거 쓰면 좋겠네요

```suggestion
        self.FC1 = torch.nn.Linear(9 * 9 * 8, hidden)
        self.FC2 = torch.nn.Linear(hidden, output)

```

2023-11-16 06:55 UTC, bindon commented on M1_test.py
> +        max_data_idx = dataList.index(max(dataList))
갑자기 camelCase 됐네요 😁 
```suggestion
        data_list = conv2d_client(data)[i].flatten().tolist()
        max_data_idx = dataList.index(max(data_list))
```

2023-11-16 06:55 UTC, bindon commented on M1_test.py
지금 각 단계에서 중복으로 들어가는 데이터들이 있어서 클래스로 만들고 재활용해도 될 것 같아요
uni_henn service 내에서 `UniHenn` 클래스를 만든다음에 생성자로 아래 친구들을 직접 만들어도 될 것 같고, 아니면 생성자 파라미터로 넣어줘도 될 것 같아요
그리고 함수들을 멤버로 만들고 파라미터는 필요한 것만 넣도록 만들구요

```python
keygen = KeyGenerator(context)
public_key = keygen.create_public_key()
secret_key = keygen.secret_key()
galois_key = keygen.create_galois_keys()
relin_keys = keygen.create_relin_keys()
encryptor = Encryptor(context, public_key)
evaluator = Evaluator(context)
decryptor = Decryptor(context, secret_key)
```

2023-11-16 06:59 UTC, JihunSKKU commented
아 현재 main이 너무 정리가 되어 있지 않아서 일단 PR을 하려고 했는데 조금 더 고친다음에 보내겠습니다!

2023-11-16 07:11 UTC, JihunSKKU commented on M1_test.py
> +import torch.nn.functional as F
예전코드에서 사용했던 코드들이 지워지면서 사용하는 부분이 없어진 것 같습니다. 
# import h5py, os
# import math
# import torch.nn.functional as F
# import torch.optim as optim
모두 지우겠습니다.

2023-11-17 00:11 UTC, bindon approved these changes
이번꺼는 그냥 합치고 다음 PR에 정리하는게 좋을 것 같네요 👍

2023-11-17 05:07 UTC, JihunSKKU commented
Structural and Partial Code Modifications

2023-11-17 05:08 UTC, JihunSKKU commented
네 알겠습니다!

2023-11-17 05:08 UTC, merged